language: python

cache:
  directories:
    - $HOME/download
    - $HOME/miniconda

before_install:
  - mkdir download
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/download/miniconda.sh
  - bash $HOME/download/miniconda.sh -b -p -u $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda env create -f environment.yml -v -v

install:
  - conda env update -f=environment.yml
  - source activate tgt

script:
  - pytest
  - pep8

after_success:
  - coveralls