sudo: required

language: python

services:
  - docker

before_install:
  - docker pull continuumio/miniconda
  - docker run -i -t continuumio/miniconda /bin/bash

install:
  - conda env create -f environment.yml
  - source activate tgt

script:
  - pytest
  - pep8

after_success:
  - coveralls