language: python

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/miniconda.sh
  - bash $HOME/miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

install:
  - conda env create -f environment.yml -v
  - source activate tgt

script:
  - python -m pytest --cov=tgt tests/
  - pycodestyle tgt/
  - pycodestyle tests/

after_success:
  - coveralls