language: python

cache:
  directories:
  - $HOME/cached
  - $HOME/downloads
  - $HOME/miniconda

install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/downloads/miniconda.sh
  - bash build/build_environment.sh
  - source activate tgt

script:
  - python -m pytest --cov=tgt tests/
  - pycodestyle --show-source tgt/
  - pycodestyle --show-source tests/

after_success:
  - coveralls