language: python

cache:
  directories:
  - $HOME/cached
  - $HOME/downloads
  - $HOME/miniconda

install:
  - bash build/build_environment.sh
  - source activate tgt
  - which python

script:
  - python -m pytest --cov=tgt tests/
  - pycodestyle --show-source tgt/
  - pycodestyle --show-source tests/

after_success:
  - coveralls