name: tgt

channels:
- defaults
- conda-forge

dependencies:
 - python>=3.6
 - numpy
 - matplotlib
 - h5py
 - dill
 - scikit-learn
 - scipy
 - pytest
 - pycodestyle
 - coveralls
 - noise
 - pytest-cov